// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Migrations need a direct (non-pooled) connection. With Supabase, set
    // DIRECT_URL to the port-5432 connection string and leave DATABASE_URL as
    // the pooled (port-6543) one the app runtime uses. DIRECT_URL is optional:
    // unset, the CLI falls back to DATABASE_URL, which is correct for a plain
    // Postgres (local, Railway) with no pooler in front.
    url: process.env["DIRECT_URL"] ?? process.env["DATABASE_URL"],
  },
});
